# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('kratki_opis', models.CharField(max_length=255)),
                ('sadrzaj', models.TextField()),
                ('vrijeme_objave', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('datoteka', models.FileField(upload_to='izvjesca')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('web', models.URLField()),
                ('tip', models.CharField(choices=[('OP', 'Operater'), ('EP', 'Elektroprivreda'), ('PO', 'Posta'), ('JI', 'Javna institucija')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
                ('web', models.URLField()),
                ('aktivnost', models.CharField(choices=[('NA', 'Napajanje'), ('MJ', 'Mjerenje'), ('RR', 'RR'), ('PA', 'Pasivna'), ('TE', 'Terminalna'), ('PR', 'Pristup'), ('SO', 'Software'), ('RA', 'Racunala')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='slike')),
                ('clanak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unis.Clanak')),
            ],
        ),
    ]
