# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grandstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('web', models.URLField(blank=True, null=True)),
                ('tip', models.CharField(choices=[('ATA', 'ATA Adapteri'), ('BIP', 'Basic IP Telefoni'), ('HIP', 'High-End IP Telefoni'), ('WIP', 'Bezicni IP Telefoni'), ('ICP', 'IP Audio konferencijski telefon'), ('AIV', 'Android IP Video Telefoni'), ('VCU', 'Video konferencijski uredaji')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TekstMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='clanak',
            name='kratki_opis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slika',
            name='clanak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unis.Clanak'),
        ),
    ]
