# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0003_auto_20180313_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('sadrzaj', models.TextField()),
                ('email_adresa', models.EmailField(max_length=254)),
            ],
        ),
    ]
