# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0004_kontakt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanak',
            options={'verbose_name_plural': 'Novosti / događaji itd.'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name_plural': 'Dokumenti (izvješća itd.)'},
        ),
        migrations.AlterModelOptions(
            name='kontakt',
            options={'verbose_name_plural': 'Ostavljene poruke'},
        ),
        migrations.AlterModelOptions(
            name='korisnik',
            options={'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partneri'},
        ),
        migrations.AlterModelOptions(
            name='slika',
            options={'verbose_name_plural': 'Slike'},
        ),
        migrations.AddField(
            model_name='tekstmarketing',
            name='naslov',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
