# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0005_auto_20180316_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tekstmarketing',
            options={'verbose_name_plural': 'Filler tekstovi'},
        ),
    ]
