# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0006_auto_20180316_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(choices=[('DI', 'Direktor'), ('MA', 'Menadžment'), ('PR', 'Prodaja i računovodstvo')], max_length=2)),
                ('uloga', models.CharField(max_length=255)),
                ('ime_prezime', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
