# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0007_zaposlenik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaposlenik',
            options={'verbose_name_plural': 'Zaposlenici'},
        ),
        migrations.AddField(
            model_name='tekstmarketing',
            name='naslov_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tekstmarketing',
            name='sadrzaj_eng',
            field=models.TextField(blank=True),
        ),
    ]
