# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unis', '0009_auto_20180327_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datoteka',
            field=models.FileField(upload_to='dokumenti'),
        ),
    ]
